/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utama;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Distributor extends javax.swing.JPanel {

    Connection con;
    private final String driver = "com.mysql.cj.jdbc.Driver";
    private final String url = "jdbc:mysql://localhost:3306/tatatoko";
    private final String user = "root";
    private final String pwd = "";
    koneksi db = new koneksi();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Barang
     */
    public Distributor() {
        initComponents();
        getColumnD();
        getDataD();
        tanggal();
        status();
    }

    public void getColumnD() {
        model.addColumn("ID");
        model.addColumn("Nama ");
        model.addColumn("Kota");
        model.addColumn("Bergabung");
        model.addColumn("Telepon");
        model.addColumn("Email");
        model.addColumn("Alamat");
        model.addColumn("No Rek");
        model.addColumn("Bank");
        model.addColumn("Ket");
        model.addColumn("Status");
        
        Tbl_Daftar_Distributor.setModel(model);
       // Tbl_Detail_Distributor.setModel(model);
        Tbl_Update_Distributor.setModel(model);

    }

    public void getDataD() {

        ResultSet hasil = db.ambilData("SELECT * FROM distributor");
        try {
            while (hasil.next()) {
                model.addRow(new Object[]{hasil.getString("id_distributor"),
                    hasil.getString("nama"), hasil.getString("kota"),
                    hasil.getString("bergabung"),hasil.getString("telepon"),
                    hasil.getString("email"), hasil.getString("alamat"),
                    hasil.getString("no_rek"), hasil.getString("bank"),
                    hasil.getString("ket"), hasil.getString("status")});
            }
            Tbl_Daftar_Distributor.setModel(model);
            //Tbl_Detail_Distributor.setModel(model);
            Tbl_Update_Distributor.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void status() {
        ResultSet hasil = db.ambilData("SELECT * FROM `status` WHERE kategori = 'Distributor'");
        try {
            while (hasil.next()) {
                // Ambil nilai dari kolom "nama" dan tambahkan ke dalam JComboBox
                Field_Tambah_Status_Distributor.addItem(hasil.getString("nama"));
                Field_Update_Status_Distributor.addItem(hasil.getString("nama"));
            }
        } catch (Exception e) {
            System.out.println("Tidak Dapat Mengambil Data");
        }

    }

    public void tanggal(){
        Date now = new Date();  
        Field_Tambah_Bergabung_Distributor.setDate(now);
    }
    
    public void autoIn() {
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, user, pwd);

            String sqlquery = "SELECT MAX(RIGHT(id_distributor,4)) AS no_auto FROM distributor";
            PreparedStatement st = con.prepareStatement(sqlquery);
            ResultSet rs = st.executeQuery();

            String no_a, no_p = "";
            int p;
            if (rs.next()) {
                no_a = Integer.toString(rs.getInt(1)+1);
                p = no_a.length();
                
                for(int i = 1; i <=4-p;i++){
                no_p = no_p + "0";
                }
                Field_Tambah_Kode_Distributor.setText("DST"+no_p+no_a);
            }
                

        } catch (Exception e) {
            Field_Tambah_Kode_Distributor.setText("");
            e.printStackTrace();
        }

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Konten_Distributor = new javax.swing.JPanel();
        pn__Distributor_Utama = new javax.swing.JPanel();
        Lb_Distributor = new javax.swing.JLabel();
        pn_Ctrl_Distributor = new javax.swing.JPanel();
        Btn_Ctrl_Distributor_Detail = new rojerusan.RSMaterialButtonRectangle();
        Btn_Ctrl_Distributor_Tambah = new rojerusan.RSMaterialButtonRectangle();
        pn_Konten_Tbl_Distributor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Daftar_Distributor = new javax.swing.JTable();
        Lb_Daftar_Distributor = new javax.swing.JLabel();
        Field_Cari_Distributor = new javax.swing.JTextField();
        Btn_Cari_Distributor = new javax.swing.JButton();
        pn__Distributor_Tambah = new javax.swing.JPanel();
        Lb_Distributor1 = new javax.swing.JLabel();
        Lb_Distributor2 = new javax.swing.JLabel();
        Lb_Distributor3 = new javax.swing.JLabel();
        pn_Konten_Tbl_Distributor_Tambah = new javax.swing.JPanel();
        Lb_Tambah_Kode_Distributor = new javax.swing.JLabel();
        Field_Tambah_Kode_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Nama_Distributor = new javax.swing.JLabel();
        Field_Tambah_Nama_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Alamat_Distributor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Field_Tambah_Alamat_Distributor = new javax.swing.JTextArea();
        Lb_Tambah_Kota_Distributor = new javax.swing.JLabel();
        Field_Tambah_Kota_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Telepon_Distributor = new javax.swing.JLabel();
        Field_Tambah_Telepon_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Email_Distributor = new javax.swing.JLabel();
        Field_Tambah_Email_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Rekening_Distributor = new javax.swing.JLabel();
        Field_Tambah_Rekening_Distributor = new javax.swing.JTextField();
        Field_Tambah_Bank_Distributor = new javax.swing.JTextField();
        Lb_Tambah_Bank_Distributor = new javax.swing.JLabel();
        Lb_Tambah_Keterangan_Distributor = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Field_Tambah_Keterangan_Distributor = new javax.swing.JTextArea();
        Btn_Tambah_Kembali_Distributor = new rojerusan.RSMaterialButtonRectangle();
        Btn_Tambah_Tambah_Distributor = new rojerusan.RSMaterialButtonRectangle();
        Lb_Tambah_Bergabung_Distributor = new javax.swing.JLabel();
        Lb_Tambah_Status_Distributor = new javax.swing.JLabel();
        Field_Tambah_Status_Distributor = new javax.swing.JComboBox<>();
        Field_Tambah_Bergabung_Distributor = new com.toedter.calendar.JDateChooser();
        pn__Distributor_Detail = new javax.swing.JPanel();
        Lb_Distributor7 = new javax.swing.JLabel();
        Lb_Distributor8 = new javax.swing.JLabel();
        Lb_Distributor9 = new javax.swing.JLabel();
        pn_Konten_Tbl_Distributor_Update = new javax.swing.JPanel();
        Lb_Update_Kode_Distributor = new javax.swing.JLabel();
        Field_Update_Kode_Distributor = new javax.swing.JTextField();
        Lb_Update_Nama_Distributor = new javax.swing.JLabel();
        Field_Update_Nama_Distributor = new javax.swing.JTextField();
        Lb_Update_Alamat_Distributor = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Field_Update_Alamat_Distributor = new javax.swing.JTextArea();
        Lb_Update_Telepon_Distributor = new javax.swing.JLabel();
        Field_Update_Telepon_Distributor = new javax.swing.JTextField();
        Lb_Update_Email_Distributor = new javax.swing.JLabel();
        Field_Update_Email_Distributor = new javax.swing.JTextField();
        Lb_Update_Rekening_Distributor = new javax.swing.JLabel();
        Field_Update_Rekening_Distributor = new javax.swing.JTextField();
        Field_Update_Bank_Distributor = new javax.swing.JTextField();
        Lb_Update_Bank_Distributor = new javax.swing.JLabel();
        Lb_Update_Keterangan_Distributor = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Field_Update_Keterangan_Distributor = new javax.swing.JTextArea();
        Btn_Update_Kembali_Distributor = new rojerusan.RSMaterialButtonRectangle();
        Btn_Update_Simpan_Distributor = new rojerusan.RSMaterialButtonRectangle();
        Btn_Cari_Update_Distributor = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        Tbl_Update_Distributor = new javax.swing.JTable();
        Lb_Update_Bergabung_Distributor = new javax.swing.JLabel();
        Field_Update_Bergabung_Distributor = new javax.swing.JTextField();
        Lb_Update_Status_Distributor = new javax.swing.JLabel();
        Field_Update_Status_Distributor = new javax.swing.JComboBox<>();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        Lb_Update_Telepon_Distributor1 = new javax.swing.JLabel();
        Field_Update_Kota_Distributor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 683));
        setLayout(new java.awt.CardLayout());

        pn_Konten_Distributor.setPreferredSize(new java.awt.Dimension(1150, 683));
        pn_Konten_Distributor.setLayout(new java.awt.CardLayout());

        pn__Distributor_Utama.setBackground(new java.awt.Color(255, 255, 255));
        pn__Distributor_Utama.setPreferredSize(new java.awt.Dimension(1150, 683));

        Lb_Distributor.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor.setText("Distributor");

        Btn_Ctrl_Distributor_Detail.setBackground(new java.awt.Color(243, 78, 36));
        Btn_Ctrl_Distributor_Detail.setText("Update");
        Btn_Ctrl_Distributor_Detail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_Ctrl_Distributor_Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ctrl_Distributor_DetailActionPerformed(evt);
            }
        });

        Btn_Ctrl_Distributor_Tambah.setBackground(new java.awt.Color(3, 0, 126));
        Btn_Ctrl_Distributor_Tambah.setText("Tambah");
        Btn_Ctrl_Distributor_Tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_Ctrl_Distributor_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ctrl_Distributor_TambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Ctrl_DistributorLayout = new javax.swing.GroupLayout(pn_Ctrl_Distributor);
        pn_Ctrl_Distributor.setLayout(pn_Ctrl_DistributorLayout);
        pn_Ctrl_DistributorLayout.setHorizontalGroup(
            pn_Ctrl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Ctrl_DistributorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Btn_Ctrl_Distributor_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Btn_Ctrl_Distributor_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_Ctrl_DistributorLayout.setVerticalGroup(
            pn_Ctrl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Ctrl_DistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_Ctrl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Ctrl_Distributor_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ctrl_Distributor_Tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        Tbl_Daftar_Distributor.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        Tbl_Daftar_Distributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Kode Distributor", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Daftar_Distributor.setRowHeight(35);
        Tbl_Daftar_Distributor.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(Tbl_Daftar_Distributor);

        Lb_Daftar_Distributor.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Daftar_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lb_Daftar_Distributor.setText("Daftar Distributor");

        Field_Cari_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Btn_Cari_Distributor.setBackground(new java.awt.Color(3, 0, 169));
        Btn_Cari_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Cari_Distributor.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cari_Distributor.setText("Cari");

        javax.swing.GroupLayout pn_Konten_Tbl_DistributorLayout = new javax.swing.GroupLayout(pn_Konten_Tbl_Distributor);
        pn_Konten_Tbl_Distributor.setLayout(pn_Konten_Tbl_DistributorLayout);
        pn_Konten_Tbl_DistributorLayout.setHorizontalGroup(
            pn_Konten_Tbl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_DistributorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_Konten_Tbl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_Konten_Tbl_DistributorLayout.createSequentialGroup()
                        .addComponent(Lb_Daftar_Distributor)
                        .addGap(275, 275, 275)
                        .addComponent(Field_Cari_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Cari_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pn_Konten_Tbl_DistributorLayout.setVerticalGroup(
            pn_Konten_Tbl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_DistributorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_Konten_Tbl_DistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Daftar_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field_Cari_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cari_Distributor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout pn__Distributor_UtamaLayout = new javax.swing.GroupLayout(pn__Distributor_Utama);
        pn__Distributor_Utama.setLayout(pn__Distributor_UtamaLayout);
        pn__Distributor_UtamaLayout.setHorizontalGroup(
            pn__Distributor_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_UtamaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn__Distributor_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lb_Distributor)
                    .addComponent(pn_Ctrl_Distributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Konten_Tbl_Distributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn__Distributor_UtamaLayout.setVerticalGroup(
            pn__Distributor_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_UtamaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Lb_Distributor)
                .addGap(66, 66, 66)
                .addComponent(pn_Ctrl_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(pn_Konten_Tbl_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_Konten_Distributor.add(pn__Distributor_Utama, "card2");

        pn__Distributor_Tambah.setBackground(new java.awt.Color(255, 255, 255));
        pn__Distributor_Tambah.setPreferredSize(new java.awt.Dimension(1150, 683));

        Lb_Distributor1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor1.setText("Distributor");

        Lb_Distributor2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor2.setText(">");

        Lb_Distributor3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor3.setText("Tambah");

        Lb_Tambah_Kode_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Kode_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Kode_Distributor.setText("Kode  :");

        Field_Tambah_Kode_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Field_Tambah_Kode_Distributor.setEnabled(false);

        Lb_Tambah_Nama_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Nama_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Nama_Distributor.setText("Nama :");

        Field_Tambah_Nama_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Field_Tambah_Nama_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Tambah_Nama_DistributorActionPerformed(evt);
            }
        });

        Lb_Tambah_Alamat_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Alamat_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Alamat_Distributor.setText("Alamat :");

        Field_Tambah_Alamat_Distributor.setColumns(20);
        Field_Tambah_Alamat_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Tambah_Alamat_Distributor.setRows(5);
        jScrollPane2.setViewportView(Field_Tambah_Alamat_Distributor);

        Lb_Tambah_Kota_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Kota_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Kota_Distributor.setText("Kota  :");

        Field_Tambah_Kota_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Tambah_Telepon_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Telepon_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Telepon_Distributor.setText("Telepon  :");

        Field_Tambah_Telepon_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Tambah_Email_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Email_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Email_Distributor.setText("Email  :");

        Field_Tambah_Email_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Tambah_Rekening_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Rekening_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Rekening_Distributor.setText("No Rek  :");

        Field_Tambah_Rekening_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Field_Tambah_Bank_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Tambah_Bank_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Bank_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Bank_Distributor.setText("Bank  :");

        Lb_Tambah_Keterangan_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Keterangan_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Keterangan_Distributor.setText("Keterangan  :");

        Field_Tambah_Keterangan_Distributor.setColumns(20);
        Field_Tambah_Keterangan_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Tambah_Keterangan_Distributor.setRows(5);
        jScrollPane3.setViewportView(Field_Tambah_Keterangan_Distributor);

        Btn_Tambah_Kembali_Distributor.setBackground(new java.awt.Color(255, 202, 0));
        Btn_Tambah_Kembali_Distributor.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Tambah_Kembali_Distributor.setText("Kembali");
        Btn_Tambah_Kembali_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Tambah_Kembali_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tambah_Kembali_DistributorActionPerformed(evt);
            }
        });

        Btn_Tambah_Tambah_Distributor.setBackground(new java.awt.Color(0, 0, 153));
        Btn_Tambah_Tambah_Distributor.setText("Tambah");
        Btn_Tambah_Tambah_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Tambah_Tambah_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tambah_Tambah_DistributorActionPerformed(evt);
            }
        });

        Lb_Tambah_Bergabung_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Bergabung_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Bergabung_Distributor.setText("Bergabung  :");

        Lb_Tambah_Status_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_Status_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_Status_Distributor.setText("Status  :");
        Lb_Tambah_Status_Distributor.setName(""); // NOI18N

        Field_Tambah_Status_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Field_Tambah_Status_Distributor.setName(""); // NOI18N
        Field_Tambah_Status_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Tambah_Status_DistributorActionPerformed(evt);
            }
        });

        Field_Tambah_Bergabung_Distributor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout pn_Konten_Tbl_Distributor_TambahLayout = new javax.swing.GroupLayout(pn_Konten_Tbl_Distributor_Tambah);
        pn_Konten_Tbl_Distributor_Tambah.setLayout(pn_Konten_Tbl_Distributor_TambahLayout);
        pn_Konten_Tbl_Distributor_TambahLayout.setHorizontalGroup(
            pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lb_Tambah_Telepon_Distributor)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(Lb_Tambah_Alamat_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Lb_Tambah_Kode_Distributor)
                                        .addComponent(Lb_Tambah_Nama_Distributor)))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb_Tambah_Email_Distributor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lb_Tambah_Status_Distributor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Field_Tambah_Nama_Distributor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Field_Tambah_Kode_Distributor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(Field_Tambah_Status_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Field_Tambah_Email_Distributor)
                                    .addComponent(Field_Tambah_Telepon_Distributor))
                                .addGap(78, 78, 78)
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Tambah_Kota_Distributor)
                                    .addComponent(Lb_Tambah_Bergabung_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Field_Tambah_Kota_Distributor)
                                    .addComponent(Field_Tambah_Bergabung_Distributor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                        .addGap(1, 1, 1)))
                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_Rekening_Distributor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Tambah_Rekening_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_Bank_Distributor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Tambah_Bank_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addComponent(Btn_Tambah_Tambah_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_Tambah_Kembali_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_Keterangan_Distributor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(313, 313, 313))
        );
        pn_Konten_Tbl_Distributor_TambahLayout.setVerticalGroup(
            pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_Kode_Distributor)
                                .addGap(36, 36, 36)
                                .addComponent(Lb_Tambah_Nama_Distributor))
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Field_Tambah_Bank_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lb_Tambah_Bank_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lb_Tambah_Keterangan_Distributor)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Field_Tambah_Telepon_Distributor)
                                .addComponent(Lb_Tambah_Kota_Distributor)
                                .addComponent(Field_Tambah_Kota_Distributor))
                            .addComponent(Lb_Tambah_Telepon_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_Tambah_Email_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Tambah_Email_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Tambah_Bergabung_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                        .addComponent(Field_Tambah_Kode_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Tambah_Rekening_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Tambah_Rekening_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(438, 438, 438)
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Tambah_Kembali_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Tambah_Tambah_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97))
                            .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(Lb_Tambah_Alamat_Distributor))
                                    .addComponent(Field_Tambah_Nama_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Field_Tambah_Status_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lb_Tambah_Status_Distributor))
                                        .addGap(207, 207, 207))
                                    .addGroup(pn_Konten_Tbl_Distributor_TambahLayout.createSequentialGroup()
                                        .addGap(235, 235, 235)
                                        .addComponent(Field_Tambah_Bergabung_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );

        javax.swing.GroupLayout pn__Distributor_TambahLayout = new javax.swing.GroupLayout(pn__Distributor_Tambah);
        pn__Distributor_Tambah.setLayout(pn__Distributor_TambahLayout);
        pn__Distributor_TambahLayout.setHorizontalGroup(
            pn__Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_TambahLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn__Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_Konten_Tbl_Distributor_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn__Distributor_TambahLayout.createSequentialGroup()
                        .addComponent(Lb_Distributor1)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Distributor2)
                        .addGap(46, 46, 46)
                        .addComponent(Lb_Distributor3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn__Distributor_TambahLayout.setVerticalGroup(
            pn__Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_TambahLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pn__Distributor_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Distributor1)
                    .addComponent(Lb_Distributor2)
                    .addComponent(Lb_Distributor3))
                .addGap(46, 46, 46)
                .addComponent(pn_Konten_Tbl_Distributor_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_Konten_Distributor.add(pn__Distributor_Tambah, "card2");

        pn__Distributor_Detail.setBackground(new java.awt.Color(255, 255, 255));
        pn__Distributor_Detail.setPreferredSize(new java.awt.Dimension(1150, 683));

        Lb_Distributor7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor7.setText("Distributor");

        Lb_Distributor8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor8.setText(">");

        Lb_Distributor9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_Distributor9.setText("Update");

        Lb_Update_Kode_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Kode_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Kode_Distributor.setText("Kode  :");

        Field_Update_Kode_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Update_Nama_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Nama_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Nama_Distributor.setText("Nama :");

        Field_Update_Nama_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Update_Alamat_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Alamat_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Alamat_Distributor.setText("Alamat :");

        Field_Update_Alamat_Distributor.setColumns(20);
        Field_Update_Alamat_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Update_Alamat_Distributor.setRows(5);
        jScrollPane7.setViewportView(Field_Update_Alamat_Distributor);

        Lb_Update_Telepon_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Telepon_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Telepon_Distributor.setText("Telepon  :");

        Field_Update_Telepon_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Update_Email_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Email_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Email_Distributor.setText("Email  :");

        Field_Update_Email_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Update_Rekening_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Rekening_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Rekening_Distributor.setText("No Rek  :");

        Field_Update_Rekening_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Field_Update_Bank_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Lb_Update_Bank_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Bank_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Bank_Distributor.setText("Bank  :");

        Lb_Update_Keterangan_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Keterangan_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Keterangan_Distributor.setText("Keterangan  :");

        Field_Update_Keterangan_Distributor.setColumns(20);
        Field_Update_Keterangan_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Update_Keterangan_Distributor.setRows(5);
        jScrollPane8.setViewportView(Field_Update_Keterangan_Distributor);

        Btn_Update_Kembali_Distributor.setBackground(new java.awt.Color(255, 202, 0));
        Btn_Update_Kembali_Distributor.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Update_Kembali_Distributor.setText("Kembali");
        Btn_Update_Kembali_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Update_Kembali_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Update_Kembali_DistributorActionPerformed(evt);
            }
        });

        Btn_Update_Simpan_Distributor.setBackground(new java.awt.Color(243, 78, 36));
        Btn_Update_Simpan_Distributor.setText("Update");
        Btn_Update_Simpan_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Update_Simpan_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Update_Simpan_DistributorActionPerformed(evt);
            }
        });

        Btn_Cari_Update_Distributor.setBackground(new java.awt.Color(3, 0, 126));
        Btn_Cari_Update_Distributor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Cari_Update_Distributor.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cari_Update_Distributor.setText("Cari");
        Btn_Cari_Update_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cari_Update_DistributorActionPerformed(evt);
            }
        });

        Tbl_Update_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tbl_Update_Distributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Distributor", "Nama", "Kota", "Provinsi", "Bergabung", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Update_Distributor.setRowHeight(30);
        Tbl_Update_Distributor.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jScrollPane9.setViewportView(Tbl_Update_Distributor);

        Lb_Update_Bergabung_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Bergabung_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Bergabung_Distributor.setText("Bergabung  :");

        Field_Update_Bergabung_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        Lb_Update_Status_Distributor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Status_Distributor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Status_Distributor.setText("Status  :");

        Field_Update_Status_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 0, 0));
        rSMaterialButtonRectangle1.setText("Hapus");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(3, 0, 126));
        rSMaterialButtonRectangle2.setText("Pilih");
        rSMaterialButtonRectangle2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });

        Lb_Update_Telepon_Distributor1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Update_Telepon_Distributor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Update_Telepon_Distributor1.setText("Kota :");

        Field_Update_Kota_Distributor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Update_Kota_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Update_Kota_DistributorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Konten_Tbl_Distributor_UpdateLayout = new javax.swing.GroupLayout(pn_Konten_Tbl_Distributor_Update);
        pn_Konten_Tbl_Distributor_Update.setLayout(pn_Konten_Tbl_Distributor_UpdateLayout);
        pn_Konten_Tbl_Distributor_UpdateLayout.setHorizontalGroup(
            pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Update_Kode_Distributor)
                                    .addComponent(Lb_Update_Nama_Distributor)
                                    .addComponent(Lb_Update_Telepon_Distributor)
                                    .addComponent(Lb_Update_Email_Distributor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Lb_Update_Status_Distributor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Field_Update_Kode_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Field_Update_Kota_Distributor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Field_Update_Status_Distributor, 0, 200, Short.MAX_VALUE))
                                        .addGap(676, 676, 676)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addComponent(Field_Update_Nama_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Cari_Update_Distributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(249, 249, 249))
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Field_Update_Email_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Field_Update_Telepon_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(Lb_Update_Alamat_Distributor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Lb_Update_Telepon_Distributor1)))
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Lb_Update_Bank_Distributor)
                        .addComponent(Lb_Update_Keterangan_Distributor)
                        .addComponent(Lb_Update_Rekening_Distributor))
                    .addComponent(Lb_Update_Bergabung_Distributor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Field_Update_Rekening_Distributor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field_Update_Bank_Distributor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field_Update_Bergabung_Distributor))
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Btn_Update_Kembali_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Update_Simpan_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pn_Konten_Tbl_Distributor_UpdateLayout.setVerticalGroup(
            pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Update_Telepon_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Telepon_Distributor))
                                .addGap(26, 26, 26)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Update_Email_Distributor)
                                    .addComponent(Field_Update_Email_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Update_Kode_Distributor)
                                    .addComponent(Field_Update_Kode_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Rekening_Distributor)
                                    .addComponent(Field_Update_Rekening_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Update_Bank_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Bank_Distributor))
                                .addGap(48, 48, 48)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Update_Bergabung_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Bergabung_Distributor))))
                        .addGap(34, 34, 34)
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Update_Kota_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Telepon_Distributor1))
                                .addGap(33, 33, 33)
                                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Update_Status_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Update_Status_Distributor)))
                            .addComponent(Lb_Update_Keterangan_Distributor)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_Update_Nama_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Update_Nama_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Cari_Update_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Update_Alamat_Distributor)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(143, 143, 143)
                .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createSequentialGroup()
                        .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Update_Simpan_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(pn_Konten_Tbl_Distributor_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Update_Kembali_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(155, 155, 155))
        );

        javax.swing.GroupLayout pn__Distributor_DetailLayout = new javax.swing.GroupLayout(pn__Distributor_Detail);
        pn__Distributor_Detail.setLayout(pn__Distributor_DetailLayout);
        pn__Distributor_DetailLayout.setHorizontalGroup(
            pn__Distributor_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_DetailLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn__Distributor_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_Konten_Tbl_Distributor_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn__Distributor_DetailLayout.createSequentialGroup()
                        .addComponent(Lb_Distributor7)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Distributor8)
                        .addGap(22, 22, 22)
                        .addComponent(Lb_Distributor9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn__Distributor_DetailLayout.setVerticalGroup(
            pn__Distributor_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn__Distributor_DetailLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pn__Distributor_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Distributor7)
                    .addComponent(Lb_Distributor8)
                    .addComponent(Lb_Distributor9))
                .addGap(43, 43, 43)
                .addComponent(pn_Konten_Tbl_Distributor_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_Konten_Distributor.add(pn__Distributor_Detail, "card2");

        add(pn_Konten_Distributor, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Ctrl_Distributor_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ctrl_Distributor_TambahActionPerformed
        pn_Konten_Distributor.removeAll();
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();

        pn_Konten_Distributor.add(pn__Distributor_Tambah);
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();
        autoIn();
        resetForm();
    }//GEN-LAST:event_Btn_Ctrl_Distributor_TambahActionPerformed

    private void Btn_Tambah_Kembali_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tambah_Kembali_DistributorActionPerformed
        pn_Konten_Distributor.removeAll();
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();

        pn_Konten_Distributor.add(pn__Distributor_Utama);
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();
    }//GEN-LAST:event_Btn_Tambah_Kembali_DistributorActionPerformed

    private void Btn_Ctrl_Distributor_DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ctrl_Distributor_DetailActionPerformed
        pn_Konten_Distributor.removeAll();
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();

        pn_Konten_Distributor.add(pn__Distributor_Detail);
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();
    }//GEN-LAST:event_Btn_Ctrl_Distributor_DetailActionPerformed

    private void Btn_Tambah_Tambah_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tambah_Tambah_DistributorActionPerformed
        String id = Field_Tambah_Kode_Distributor.getText();
        String nama = Field_Tambah_Nama_Distributor.getText();
        String alamat = Field_Tambah_Alamat_Distributor.getText();
        String kota = Field_Tambah_Kota_Distributor.getText();
        String telepon = Field_Tambah_Telepon_Distributor.getText();
        String email = Field_Tambah_Email_Distributor.getText();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String bergabung = date.format(Field_Tambah_Bergabung_Distributor.getDate());
        String status = String.valueOf(Field_Tambah_Status_Distributor.getSelectedItem());
        String no_rek = Field_Tambah_Rekening_Distributor.getText();
        String bank = Field_Tambah_Bank_Distributor.getText();
        String ket = Field_Tambah_Keterangan_Distributor.getText();

        try {
            db.aksi("INSERT INTO distributor VALUES ('" + id + "','" + nama + "','" + kota + "','" + bergabung + "','" + telepon + "','" + email + "','" + alamat + "','" + no_rek + "','" + bank + "','" + ket + "','" + status + "')");
            model.setRowCount(0);
            Tbl_Daftar_Distributor.setModel(model);
          //  Tbl_Detail_Distributor.setModel(model);
            Tbl_Update_Distributor.setModel(model);
            getDataD();
            autoIn();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
            pn_Konten_Distributor.removeAll();
            pn_Konten_Distributor.repaint();
            pn_Konten_Distributor.revalidate();

            pn_Konten_Distributor.add(pn__Distributor_Utama);
            pn_Konten_Distributor.repaint();
            pn_Konten_Distributor.revalidate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan: " + e.getMessage());
        }

    }//GEN-LAST:event_Btn_Tambah_Tambah_DistributorActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        int selectedRow = Tbl_Update_Distributor.getSelectedRow();
        
        Field_Update_Kode_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 0)));
        Field_Update_Nama_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 1)));
        Field_Update_Kota_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 2)));
        Field_Update_Bergabung_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 3)));
        Field_Update_Telepon_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 4)));
        Field_Update_Email_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 5)));
        Field_Update_Alamat_Distributor.setText(String.valueOf( Tbl_Update_Distributor.getValueAt(selectedRow, 6)));
        Field_Update_Rekening_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 7)));
        Field_Update_Bank_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 8)));
        Field_Update_Keterangan_Distributor.setText(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 9)));
        Field_Update_Status_Distributor.setSelectedItem(String.valueOf(Tbl_Update_Distributor.getValueAt(selectedRow, 10)));
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        int Row = Tbl_Update_Distributor.getSelectedRow();
        String ID = (String) Tbl_Update_Distributor.getValueAt(Row, 0);
        db.aksi("DELETE FROM distributor WHERE id_distributor='"+ID+"'");
        model.setRowCount(0);
        Tbl_Update_Distributor.setModel(model);
        getDataD();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void Btn_Cari_Update_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cari_Update_DistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cari_Update_DistributorActionPerformed

    private void Btn_Update_Kembali_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Update_Kembali_DistributorActionPerformed
        pn_Konten_Distributor.removeAll();
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();

        pn_Konten_Distributor.add(pn__Distributor_Utama);
        pn_Konten_Distributor.repaint();
        pn_Konten_Distributor.revalidate();
    }//GEN-LAST:event_Btn_Update_Kembali_DistributorActionPerformed

    private void Btn_Update_Simpan_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Update_Simpan_DistributorActionPerformed
        
        int Row = Tbl_Update_Distributor.getSelectedRow();
        String ID = (String) Tbl_Update_Distributor.getValueAt(Row, 0);
        db.aksi("UPDATE distributor SET nama = '"+Field_Update_Nama_Distributor.getText()+
            "',kota = '"+Field_Update_Kota_Distributor.getText()+"',bergabung = '"+Field_Update_Bergabung_Distributor.getText()+
            "',telepon = '"+Field_Update_Telepon_Distributor.getText()+ "',email = '"+Field_Update_Email_Distributor.getText()+
            "',alamat = '"+Field_Update_Alamat_Distributor.getText()+"',no_rek = '"+Field_Update_Rekening_Distributor.getText()+
            "',bank = '"+Field_Update_Bank_Distributor.getText()+
            "',ket = '"+Field_Update_Keterangan_Distributor.getText()+"',status = '"+Field_Update_Status_Distributor.getSelectedItem()+
            "' WHERE id_distributor = '"+Field_Update_Kode_Distributor.getText()+"'");
        model.setRowCount(0);
        Tbl_Update_Distributor.setModel(model);
        getDataD();
        resetFormUpdate();
    }//GEN-LAST:event_Btn_Update_Simpan_DistributorActionPerformed

    private void Field_Update_Kota_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Update_Kota_DistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Update_Kota_DistributorActionPerformed

    private void Field_Tambah_Nama_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Tambah_Nama_DistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Tambah_Nama_DistributorActionPerformed

    private void Field_Tambah_Status_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Tambah_Status_DistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Tambah_Status_DistributorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cari_Distributor;
    private javax.swing.JButton Btn_Cari_Update_Distributor;
    private rojerusan.RSMaterialButtonRectangle Btn_Ctrl_Distributor_Detail;
    private rojerusan.RSMaterialButtonRectangle Btn_Ctrl_Distributor_Tambah;
    private rojerusan.RSMaterialButtonRectangle Btn_Tambah_Kembali_Distributor;
    private rojerusan.RSMaterialButtonRectangle Btn_Tambah_Tambah_Distributor;
    private rojerusan.RSMaterialButtonRectangle Btn_Update_Kembali_Distributor;
    private rojerusan.RSMaterialButtonRectangle Btn_Update_Simpan_Distributor;
    private javax.swing.JTextField Field_Cari_Distributor;
    private javax.swing.JTextArea Field_Tambah_Alamat_Distributor;
    private javax.swing.JTextField Field_Tambah_Bank_Distributor;
    private com.toedter.calendar.JDateChooser Field_Tambah_Bergabung_Distributor;
    private javax.swing.JTextField Field_Tambah_Email_Distributor;
    private javax.swing.JTextArea Field_Tambah_Keterangan_Distributor;
    private javax.swing.JTextField Field_Tambah_Kode_Distributor;
    private javax.swing.JTextField Field_Tambah_Kota_Distributor;
    private javax.swing.JTextField Field_Tambah_Nama_Distributor;
    private javax.swing.JTextField Field_Tambah_Rekening_Distributor;
    private javax.swing.JComboBox<String> Field_Tambah_Status_Distributor;
    private javax.swing.JTextField Field_Tambah_Telepon_Distributor;
    private javax.swing.JTextArea Field_Update_Alamat_Distributor;
    private javax.swing.JTextField Field_Update_Bank_Distributor;
    private javax.swing.JTextField Field_Update_Bergabung_Distributor;
    private javax.swing.JTextField Field_Update_Email_Distributor;
    private javax.swing.JTextArea Field_Update_Keterangan_Distributor;
    private javax.swing.JTextField Field_Update_Kode_Distributor;
    private javax.swing.JTextField Field_Update_Kota_Distributor;
    private javax.swing.JTextField Field_Update_Nama_Distributor;
    private javax.swing.JTextField Field_Update_Rekening_Distributor;
    private javax.swing.JComboBox<String> Field_Update_Status_Distributor;
    private javax.swing.JTextField Field_Update_Telepon_Distributor;
    private javax.swing.JLabel Lb_Daftar_Distributor;
    private javax.swing.JLabel Lb_Distributor;
    private javax.swing.JLabel Lb_Distributor1;
    private javax.swing.JLabel Lb_Distributor2;
    private javax.swing.JLabel Lb_Distributor3;
    private javax.swing.JLabel Lb_Distributor7;
    private javax.swing.JLabel Lb_Distributor8;
    private javax.swing.JLabel Lb_Distributor9;
    private javax.swing.JLabel Lb_Tambah_Alamat_Distributor;
    private javax.swing.JLabel Lb_Tambah_Bank_Distributor;
    private javax.swing.JLabel Lb_Tambah_Bergabung_Distributor;
    private javax.swing.JLabel Lb_Tambah_Email_Distributor;
    private javax.swing.JLabel Lb_Tambah_Keterangan_Distributor;
    private javax.swing.JLabel Lb_Tambah_Kode_Distributor;
    private javax.swing.JLabel Lb_Tambah_Kota_Distributor;
    private javax.swing.JLabel Lb_Tambah_Nama_Distributor;
    private javax.swing.JLabel Lb_Tambah_Rekening_Distributor;
    private javax.swing.JLabel Lb_Tambah_Status_Distributor;
    private javax.swing.JLabel Lb_Tambah_Telepon_Distributor;
    private javax.swing.JLabel Lb_Update_Alamat_Distributor;
    private javax.swing.JLabel Lb_Update_Bank_Distributor;
    private javax.swing.JLabel Lb_Update_Bergabung_Distributor;
    private javax.swing.JLabel Lb_Update_Email_Distributor;
    private javax.swing.JLabel Lb_Update_Keterangan_Distributor;
    private javax.swing.JLabel Lb_Update_Kode_Distributor;
    private javax.swing.JLabel Lb_Update_Nama_Distributor;
    private javax.swing.JLabel Lb_Update_Rekening_Distributor;
    private javax.swing.JLabel Lb_Update_Status_Distributor;
    private javax.swing.JLabel Lb_Update_Telepon_Distributor;
    private javax.swing.JLabel Lb_Update_Telepon_Distributor1;
    private javax.swing.JTable Tbl_Daftar_Distributor;
    private javax.swing.JTable Tbl_Update_Distributor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pn_Ctrl_Distributor;
    private javax.swing.JPanel pn_Konten_Distributor;
    private javax.swing.JPanel pn_Konten_Tbl_Distributor;
    private javax.swing.JPanel pn_Konten_Tbl_Distributor_Tambah;
    private javax.swing.JPanel pn_Konten_Tbl_Distributor_Update;
    private javax.swing.JPanel pn__Distributor_Detail;
    private javax.swing.JPanel pn__Distributor_Tambah;
    private javax.swing.JPanel pn__Distributor_Utama;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    // End of variables declaration//GEN-END:variables

private void resetForm() {
        //Field_Tambah_Kode_Distributor.setText("");
        Field_Tambah_Nama_Distributor.setText("");
        Field_Tambah_Alamat_Distributor.setText("");
        Field_Tambah_Kota_Distributor.setText("");
        Field_Tambah_Telepon_Distributor.setText("");
        Field_Tambah_Email_Distributor.setText("");
        //Field_Tambah_Bergabung_Distributor.setText("");
        //Field_Tambah_Fax_Distributor.setText("");
        Field_Tambah_Status_Distributor.equals("");
        Field_Tambah_Rekening_Distributor.setText("");
        //Field_Tambah_Nama_Rekening_Distributor.setText("");
        Field_Tambah_Bank_Distributor.setText("");
       // Field_Tambah_NPWP_Distributor.setText("");
        Field_Tambah_Keterangan_Distributor.setText("");
     }

    private void resetFormUpdate() {
        Field_Update_Kode_Distributor.setText("");
        Field_Update_Nama_Distributor.setText("");
        Field_Update_Alamat_Distributor.setText("");
        Field_Update_Kota_Distributor.setText("");
        Field_Update_Telepon_Distributor.setText("");
        Field_Update_Email_Distributor.setText("");
        Field_Update_Bergabung_Distributor.setText("");
        //Field_Update_Fax_Distributor.setText("");
        Field_Update_Status_Distributor.equals("");
        Field_Update_Rekening_Distributor.setText("");
        //Field_Update_Nama_Rekening_Distributor.setText("");
        Field_Update_Bank_Distributor.setText("");
        //Field_Update_NPWP_Distributor.setText("");
        Field_Update_Keterangan_Distributor.setText("");
    }
}


