/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utama;

/**
 *
 * @author acer
 */
public class Hutang extends javax.swing.JPanel {

    /**
     * Creates new form Beranda
     */
    public Hutang() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Hutang = new javax.swing.JPanel();
        Lb_Hutang = new javax.swing.JLabel();
        Btn_Daftar_Hutang = new javax.swing.JButton();
        Btn_Tambah_Hutang = new javax.swing.JButton();
        Btn_Detail_Hutang = new javax.swing.JButton();
        pn_Konten_Hutang = new javax.swing.JPanel();
        pn_Daftar_Hutang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Daftar_Hutang = new javax.swing.JTable();
        Lb_Hutang_Cari_No_Hutang = new javax.swing.JLabel();
        Field_Hutang_Cari_No_Hutang = new javax.swing.JTextField();
        Btn_Hutang_Cari_No_Hutang = new javax.swing.JButton();
        Lb_Daftar_Hutang = new javax.swing.JLabel();
        pn_Tambah_Hutang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Daftar_Detail_Barang_Hutang = new javax.swing.JTable();
        Lb_Hutang_Tambah_No_Hutang = new javax.swing.JLabel();
        Field_Hutang_Tambah_No_Hutang = new javax.swing.JTextField();
        Lb_Daftar_Hutang1 = new javax.swing.JLabel();
        Btn_Hutang_Tambah_Simpan = new javax.swing.JButton();
        Btn_Hutang_Tambah_Kembali = new javax.swing.JButton();
        Btn_Hutang_Cetak_Bukti = new javax.swing.JButton();
        Lb_Hutang_Tambah_No_Transaksi = new javax.swing.JLabel();
        Field_Hutang_Tambah_No_Transaksi = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Tanggal_Hutang = new javax.swing.JLabel();
        Field_Hutang_Tambah_Tanggal_Hutang = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Jatuh_Tempo = new javax.swing.JLabel();
        Field_Hutang_Tambah_Jatuh_Tempo = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Nama_Kasir = new javax.swing.JLabel();
        Field_Hutang_Tambah_Kasir = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Nama_Pelanggan = new javax.swing.JLabel();
        Field_Hutang_Tambah_Pelanggan = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Id_Pelanggan = new javax.swing.JLabel();
        Field_Hutang_Tambah_Id_Pelanggan = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Alamat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Field_Hutang_Tambah_Alamat = new javax.swing.JTextArea();
        Lb_Hutang_Tambah_No_Telepon = new javax.swing.JLabel();
        Field_Hutang_Tambah_No_Telepon = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Harga_Total = new javax.swing.JLabel();
        Lb_Hutang_Tambah_Denda = new javax.swing.JLabel();
        Field_Hutang_Tambah_Harga_Total = new javax.swing.JTextField();
        Field_Hutang_Tambah_Denda = new javax.swing.JTextField();
        Lb_Hutang_Tambah_Catatan = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Field_Hutang_Tambah_Catatan = new javax.swing.JTextArea();
        Btn_Hutang_Tambah_Barang_Hutang = new javax.swing.JButton();
        Field_Hutang_Tambah_Barang_Barang = new javax.swing.JTextField();
        pn_Detail_Hutang = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tbl_Detail_Barang_Hutang = new javax.swing.JTable();
        Lb_Hutang_Detail_No_Hutang = new javax.swing.JLabel();
        Field_Hutang_Detail_No_Hutang = new javax.swing.JTextField();
        Lb_Detail_Barang_Hutang = new javax.swing.JLabel();
        Lb_Hutang_Detail_No_Transaksi = new javax.swing.JLabel();
        Field_Hutang_Detail_No_Transaksi = new javax.swing.JTextField();
        Lb_Hutang_Detail_Tanggal_Hutang = new javax.swing.JLabel();
        Field_Hutang_Detail_Tanggal_Hutang = new javax.swing.JTextField();
        Lb_Hutang_Detail_Jatuh_Tempo = new javax.swing.JLabel();
        Field_Hutang_Detail_Jatuh_Tempo = new javax.swing.JTextField();
        Lb_Hutang_Detail_Nama_Kasir = new javax.swing.JLabel();
        Field_Hutang_Detail_Kasir = new javax.swing.JTextField();
        Lb_Hutang_Detail_Nama_Pelanggan = new javax.swing.JLabel();
        Field_Hutang_Detail_Pelanggan = new javax.swing.JTextField();
        Lb_Hutang_Detail_Id_Pelanggan = new javax.swing.JLabel();
        Field_Hutang_Detail_Id_Pelanggan = new javax.swing.JTextField();
        Lb_Hutang_Detail_Alamat = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Field_Hutang_Detail_Alamat = new javax.swing.JTextArea();
        Lb_Hutang_Detail_No_Telepon = new javax.swing.JLabel();
        Field_Hutang_Tambah_No_Telepon1 = new javax.swing.JTextField();
        Lb_Hutang_Detail_Harga_Total = new javax.swing.JLabel();
        Lb_Hutang_Detail_Denda = new javax.swing.JLabel();
        Field_Hutang_Detail_Harga_Total = new javax.swing.JTextField();
        Field_Hutang_Detail_Denda = new javax.swing.JTextField();
        Lb_Hutang_Detail_Catatan = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Field_Hutang_Detail_Catatan = new javax.swing.JTextArea();
        Lb_Hutang_Detail_Status = new javax.swing.JLabel();
        Field_Hutang_Detail_Status = new javax.swing.JComboBox<>();
        Btn_SImpan_Detail_Hutang = new javax.swing.JButton();
        Btn_Update_Detail_Hutang = new javax.swing.JButton();
        Btn_Kembali_Detail_Hutang = new javax.swing.JButton();
        Lb_Hutang_Detail_Terlambat = new javax.swing.JLabel();
        Field_Hutang_Detail_Terlambat = new javax.swing.JTextField();
        Btn_Detail_Hapus_Hutang = new javax.swing.JButton();
        Field_Detail_Tambah_Barang_Hutang = new javax.swing.JTextField();
        Btn_Detail_Barang_Hutang = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1182, 686));

        pn_Hutang.setBackground(new java.awt.Color(255, 255, 255));
        pn_Hutang.setPreferredSize(new java.awt.Dimension(1182, 686));

        Lb_Hutang.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        Lb_Hutang.setText("Hutang");

        Btn_Daftar_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Daftar_Hutang.setText("Daftar Hutang");
        Btn_Daftar_Hutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Daftar_HutangMouseClicked(evt);
            }
        });

        Btn_Tambah_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Tambah_Hutang.setText("Tambah");
        Btn_Tambah_Hutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Tambah_HutangMouseClicked(evt);
            }
        });

        Btn_Detail_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Detail_Hutang.setText("Detail");
        Btn_Detail_Hutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Detail_HutangMouseClicked(evt);
            }
        });

        pn_Konten_Hutang.setLayout(new java.awt.CardLayout());

        Tbl_Daftar_Hutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Daftar_Hutang);

        Lb_Hutang_Cari_No_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Cari_No_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Cari_No_Hutang.setText("No Hutang :");

        Btn_Hutang_Cari_No_Hutang.setBackground(new java.awt.Color(3, 0, 126));
        Btn_Hutang_Cari_No_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_Hutang_Cari_No_Hutang.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Hutang_Cari_No_Hutang.setText("Cari");

        Lb_Daftar_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Daftar_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Daftar_Hutang.setText("Daftar Hutang");

        javax.swing.GroupLayout pn_Daftar_HutangLayout = new javax.swing.GroupLayout(pn_Daftar_Hutang);
        pn_Daftar_Hutang.setLayout(pn_Daftar_HutangLayout);
        pn_Daftar_HutangLayout.setHorizontalGroup(
            pn_Daftar_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Daftar_HutangLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Lb_Hutang_Cari_No_Hutang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Hutang_Cari_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Hutang_Cari_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_HutangLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(pn_Daftar_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_HutangLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_HutangLayout.createSequentialGroup()
                        .addComponent(Lb_Daftar_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(449, 449, 449))))
        );
        pn_Daftar_HutangLayout.setVerticalGroup(
            pn_Daftar_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Daftar_HutangLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pn_Daftar_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Hutang_Cari_No_Hutang)
                    .addComponent(Field_Hutang_Cari_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Hutang_Cari_No_Hutang))
                .addGap(46, 46, 46)
                .addComponent(Lb_Daftar_Hutang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pn_Konten_Hutang.add(pn_Daftar_Hutang, "card2");

        Tbl_Daftar_Detail_Barang_Hutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tbl_Daftar_Detail_Barang_Hutang);

        Lb_Hutang_Tambah_No_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_No_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_No_Hutang.setText("No Hutang :");

        Lb_Daftar_Hutang1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Daftar_Hutang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Daftar_Hutang1.setText("Detail Barang Hutang");

        Btn_Hutang_Tambah_Simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Hutang_Tambah_Simpan.setText("Simpan");

        Btn_Hutang_Tambah_Kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Hutang_Tambah_Kembali.setText("Kembali");
        Btn_Hutang_Tambah_Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Hutang_Tambah_KembaliMouseClicked(evt);
            }
        });

        Btn_Hutang_Cetak_Bukti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Hutang_Cetak_Bukti.setText("Cetak Bukti");

        Lb_Hutang_Tambah_No_Transaksi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_No_Transaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_No_Transaksi.setText("No Transaksi :");

        Lb_Hutang_Tambah_Tanggal_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Tanggal_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Tanggal_Hutang.setText("Tanggal Hutang :");

        Lb_Hutang_Tambah_Jatuh_Tempo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Jatuh_Tempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Jatuh_Tempo.setText("Jatuh Tempo :");

        Lb_Hutang_Tambah_Nama_Kasir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Nama_Kasir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Nama_Kasir.setText("Kasir :");

        Lb_Hutang_Tambah_Nama_Pelanggan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Nama_Pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Nama_Pelanggan.setText("Pelanggan :");

        Lb_Hutang_Tambah_Id_Pelanggan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Id_Pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Id_Pelanggan.setText("ID Pelanggan :");

        Lb_Hutang_Tambah_Alamat.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Alamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Alamat.setText("Alamat :");

        Field_Hutang_Tambah_Alamat.setColumns(20);
        Field_Hutang_Tambah_Alamat.setRows(5);
        jScrollPane3.setViewportView(Field_Hutang_Tambah_Alamat);

        Lb_Hutang_Tambah_No_Telepon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_No_Telepon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_No_Telepon.setText("No Telepon :");

        Lb_Hutang_Tambah_Harga_Total.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Harga_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Harga_Total.setText("Harga Total :");

        Lb_Hutang_Tambah_Denda.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Denda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Tambah_Denda.setText("Denda :");

        Lb_Hutang_Tambah_Catatan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Tambah_Catatan.setText("Catatan :");

        Field_Hutang_Tambah_Catatan.setColumns(20);
        Field_Hutang_Tambah_Catatan.setRows(5);
        jScrollPane4.setViewportView(Field_Hutang_Tambah_Catatan);

        Btn_Hutang_Tambah_Barang_Hutang.setBackground(new java.awt.Color(3, 0, 126));
        Btn_Hutang_Tambah_Barang_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Hutang_Tambah_Barang_Hutang.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Hutang_Tambah_Barang_Hutang.setText("Tambah");

        javax.swing.GroupLayout pn_Tambah_HutangLayout = new javax.swing.GroupLayout(pn_Tambah_Hutang);
        pn_Tambah_Hutang.setLayout(pn_Tambah_HutangLayout);
        pn_Tambah_HutangLayout.setHorizontalGroup(
            pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Tambah_No_Hutang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Tambah_No_Transaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_No_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Tambah_Tanggal_Hutang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_Tanggal_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Tambah_Jatuh_Tempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_Jatuh_Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Tambah_Nama_Kasir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_Kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                        .addComponent(Lb_Hutang_Tambah_No_Telepon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Field_Hutang_Tambah_No_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                        .addComponent(Lb_Hutang_Tambah_Nama_Pelanggan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Field_Hutang_Tambah_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                        .addComponent(Lb_Hutang_Tambah_Id_Pelanggan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Field_Hutang_Tambah_Id_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(Lb_Hutang_Tambah_Alamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_HutangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lb_Daftar_Hutang1)
                                .addGap(112, 112, 112)
                                .addComponent(Field_Hutang_Tambah_Barang_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Hutang_Tambah_Barang_Hutang)
                                .addGap(16, 16, 16))))
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                        .addComponent(Lb_Hutang_Tambah_Catatan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                        .addComponent(Btn_Hutang_Tambah_Simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_Hutang_Tambah_Kembali)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_Hutang_Cetak_Bukti)
                                        .addGap(78, 78, 78)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_Hutang_Tambah_Denda, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Hutang_Tambah_Harga_Total, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Field_Hutang_Tambah_Harga_Total)
                                    .addComponent(Field_Hutang_Tambah_Denda))))
                        .addGap(16, 16, 16)))
                .addGap(30, 30, 30))
        );
        pn_Tambah_HutangLayout.setVerticalGroup(
            pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_No_Hutang)
                            .addComponent(Field_Hutang_Tambah_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_No_Transaksi)
                            .addComponent(Field_Hutang_Tambah_No_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_Tanggal_Hutang)
                            .addComponent(Field_Hutang_Tambah_Tanggal_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_Jatuh_Tempo)
                            .addComponent(Field_Hutang_Tambah_Jatuh_Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_Nama_Kasir)
                            .addComponent(Field_Hutang_Tambah_Kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Hutang_Tambah_Alamat)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Tambah_Nama_Pelanggan)
                                    .addComponent(Field_Hutang_Tambah_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Tambah_Id_Pelanggan)
                                    .addComponent(Field_Hutang_Tambah_Id_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Tambah_No_Telepon)
                                    .addComponent(Field_Hutang_Tambah_No_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lb_Daftar_Hutang1)
                            .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Btn_Hutang_Tambah_Barang_Hutang)
                                .addComponent(Field_Hutang_Tambah_Barang_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addComponent(Lb_Hutang_Tambah_Catatan)
                        .addGap(24, 24, 24)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Hutang_Tambah_Simpan)
                            .addComponent(Btn_Hutang_Tambah_Kembali)
                            .addComponent(Btn_Hutang_Cetak_Bukti)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_Tambah_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_Harga_Total)
                            .addComponent(Field_Hutang_Tambah_Harga_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Tambah_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Tambah_Denda)
                            .addComponent(Field_Hutang_Tambah_Denda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pn_Konten_Hutang.add(pn_Tambah_Hutang, "card2");

        Tbl_Detail_Barang_Hutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(Tbl_Detail_Barang_Hutang);

        Lb_Hutang_Detail_No_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_No_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_No_Hutang.setText("No Hutang :");

        Lb_Detail_Barang_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Detail_Barang_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Detail_Barang_Hutang.setText("Barang Hutang");

        Lb_Hutang_Detail_No_Transaksi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_No_Transaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_No_Transaksi.setText("No Transaksi :");

        Lb_Hutang_Detail_Tanggal_Hutang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Tanggal_Hutang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Tanggal_Hutang.setText("Tanggal Hutang :");

        Lb_Hutang_Detail_Jatuh_Tempo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Jatuh_Tempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Jatuh_Tempo.setText("Jatuh Tempo :");

        Lb_Hutang_Detail_Nama_Kasir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Nama_Kasir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Nama_Kasir.setText("Kasir :");

        Lb_Hutang_Detail_Nama_Pelanggan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Nama_Pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Nama_Pelanggan.setText("Pelanggan :");

        Lb_Hutang_Detail_Id_Pelanggan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Id_Pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Id_Pelanggan.setText("ID Pelanggan :");

        Lb_Hutang_Detail_Alamat.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Alamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Alamat.setText("Alamat :");

        Field_Hutang_Detail_Alamat.setColumns(20);
        Field_Hutang_Detail_Alamat.setRows(5);
        jScrollPane6.setViewportView(Field_Hutang_Detail_Alamat);

        Lb_Hutang_Detail_No_Telepon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_No_Telepon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_No_Telepon.setText("No Telepon :");

        Lb_Hutang_Detail_Harga_Total.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Harga_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Harga_Total.setText("Harga Total :");

        Lb_Hutang_Detail_Denda.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Denda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Denda.setText("Denda :");

        Lb_Hutang_Detail_Catatan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Catatan.setText("Catatan :");

        Field_Hutang_Detail_Catatan.setColumns(20);
        Field_Hutang_Detail_Catatan.setRows(5);
        jScrollPane7.setViewportView(Field_Hutang_Detail_Catatan);

        Lb_Hutang_Detail_Status.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Status.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Status.setText("Status :");

        Field_Hutang_Detail_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Btn_SImpan_Detail_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_SImpan_Detail_Hutang.setText("Simpan");

        Btn_Update_Detail_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Update_Detail_Hutang.setText("Update");

        Btn_Kembali_Detail_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Kembali_Detail_Hutang.setText("Kembali");
        Btn_Kembali_Detail_Hutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Kembali_Detail_HutangMouseClicked(evt);
            }
        });

        Lb_Hutang_Detail_Terlambat.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Hutang_Detail_Terlambat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Hutang_Detail_Terlambat.setText("Terlambat :");

        Btn_Detail_Hapus_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Detail_Hapus_Hutang.setText("Hapus");

        Btn_Detail_Barang_Hutang.setBackground(new java.awt.Color(3, 0, 126));
        Btn_Detail_Barang_Hutang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_Detail_Barang_Hutang.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Detail_Barang_Hutang.setText("Tambah");

        javax.swing.GroupLayout pn_Detail_HutangLayout = new javax.swing.GroupLayout(pn_Detail_Hutang);
        pn_Detail_Hutang.setLayout(pn_Detail_HutangLayout);
        pn_Detail_HutangLayout.setHorizontalGroup(
            pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_No_Hutang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_No_Transaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_No_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Tanggal_Hutang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Tanggal_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Jatuh_Tempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Jatuh_Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Nama_Kasir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Denda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Denda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_Hutang_Detail_Terlambat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Hutang_Detail_Status, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Hutang_Detail_Harga_Total))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Field_Hutang_Detail_Harga_Total)
                                    .addComponent(Field_Hutang_Detail_Terlambat)
                                    .addComponent(Field_Hutang_Detail_Status, 0, 150, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Nama_Pelanggan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_Id_Pelanggan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Detail_Id_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Hutang_Detail_No_Telepon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Hutang_Tambah_No_Telepon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addComponent(Lb_Detail_Barang_Hutang)
                                .addGap(113, 113, 113)
                                .addComponent(Field_Detail_Tambah_Barang_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Detail_Barang_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Hutang_Detail_Alamat)
                                    .addComponent(Lb_Hutang_Detail_Catatan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Btn_Update_Detail_Hutang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                        .addComponent(Btn_SImpan_Detail_Hutang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn_Kembali_Detail_Hutang)))
                                .addGap(43, 43, 43)
                                .addComponent(Btn_Detail_Hapus_Hutang)))))
                .addGap(29, 29, 29))
        );
        pn_Detail_HutangLayout.setVerticalGroup(
            pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Detail_Nama_Pelanggan)
                            .addComponent(Field_Hutang_Detail_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Detail_Id_Pelanggan)
                            .addComponent(Field_Hutang_Detail_Id_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Detail_No_Telepon)
                            .addComponent(Field_Hutang_Tambah_No_Telepon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Hutang_Detail_Alamat))
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Lb_Hutang_Detail_Catatan))
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(Btn_Update_Detail_Hutang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_SImpan_Detail_Hutang)
                            .addComponent(Btn_Kembali_Detail_Hutang)
                            .addComponent(Btn_Detail_Hapus_Hutang)))
                    .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Detail_HutangLayout.createSequentialGroup()
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Detail_No_Hutang)
                                    .addComponent(Field_Hutang_Detail_No_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Detail_No_Transaksi)
                                    .addComponent(Field_Hutang_Detail_No_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Hutang_Detail_Terlambat)
                                    .addComponent(Field_Hutang_Detail_Terlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lb_Hutang_Detail_Tanggal_Hutang)
                                    .addComponent(Field_Hutang_Detail_Tanggal_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Hutang_Detail_Denda)
                                    .addComponent(Field_Hutang_Detail_Denda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lb_Hutang_Detail_Harga_Total)
                                .addComponent(Field_Hutang_Detail_Harga_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Field_Hutang_Detail_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lb_Hutang_Detail_Status))
                            .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lb_Hutang_Detail_Jatuh_Tempo)
                                .addComponent(Field_Hutang_Detail_Jatuh_Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hutang_Detail_Nama_Kasir)
                            .addComponent(Field_Hutang_Detail_Kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_Detail_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_Detail_Tambah_Barang_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Detail_Barang_Hutang)
                            .addComponent(Lb_Detail_Barang_Hutang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pn_Konten_Hutang.add(pn_Detail_Hutang, "card2");

        javax.swing.GroupLayout pn_HutangLayout = new javax.swing.GroupLayout(pn_Hutang);
        pn_Hutang.setLayout(pn_HutangLayout);
        pn_HutangLayout.setHorizontalGroup(
            pn_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HutangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_HutangLayout.createSequentialGroup()
                        .addComponent(Btn_Daftar_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Tambah_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Btn_Detail_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_Konten_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Hutang))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pn_HutangLayout.setVerticalGroup(
            pn_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HutangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Lb_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(pn_HutangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Daftar_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Btn_Tambah_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Detail_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Konten_Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Hutang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Daftar_HutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Daftar_HutangMouseClicked
        pn_Konten_Hutang.removeAll();
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
        
        pn_Konten_Hutang.add(pn_Daftar_Hutang);
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
    }//GEN-LAST:event_Btn_Daftar_HutangMouseClicked

    private void Btn_Tambah_HutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Tambah_HutangMouseClicked
        pn_Konten_Hutang.removeAll();
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
        
        pn_Konten_Hutang.add(pn_Tambah_Hutang);
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
    }//GEN-LAST:event_Btn_Tambah_HutangMouseClicked

    private void Btn_Detail_HutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Detail_HutangMouseClicked
        pn_Konten_Hutang.removeAll();
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
        
        pn_Konten_Hutang.add(pn_Detail_Hutang);
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
    }//GEN-LAST:event_Btn_Detail_HutangMouseClicked

    private void Btn_Hutang_Tambah_KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Hutang_Tambah_KembaliMouseClicked
        pn_Konten_Hutang.removeAll();
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
        
        pn_Konten_Hutang.add(pn_Daftar_Hutang);
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
    }//GEN-LAST:event_Btn_Hutang_Tambah_KembaliMouseClicked

    private void Btn_Kembali_Detail_HutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Kembali_Detail_HutangMouseClicked
        pn_Konten_Hutang.removeAll();
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
        
        pn_Konten_Hutang.add(pn_Daftar_Hutang);
        pn_Konten_Hutang.repaint();
        pn_Konten_Hutang.revalidate();
    }//GEN-LAST:event_Btn_Kembali_Detail_HutangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Daftar_Hutang;
    private javax.swing.JButton Btn_Detail_Barang_Hutang;
    private javax.swing.JButton Btn_Detail_Hapus_Hutang;
    private javax.swing.JButton Btn_Detail_Hutang;
    private javax.swing.JButton Btn_Hutang_Cari_No_Hutang;
    private javax.swing.JButton Btn_Hutang_Cetak_Bukti;
    private javax.swing.JButton Btn_Hutang_Tambah_Barang_Hutang;
    private javax.swing.JButton Btn_Hutang_Tambah_Kembali;
    private javax.swing.JButton Btn_Hutang_Tambah_Simpan;
    private javax.swing.JButton Btn_Kembali_Detail_Hutang;
    private javax.swing.JButton Btn_SImpan_Detail_Hutang;
    private javax.swing.JButton Btn_Tambah_Hutang;
    private javax.swing.JButton Btn_Update_Detail_Hutang;
    private javax.swing.JTextField Field_Detail_Tambah_Barang_Hutang;
    private javax.swing.JTextField Field_Hutang_Cari_No_Hutang;
    private javax.swing.JTextArea Field_Hutang_Detail_Alamat;
    private javax.swing.JTextArea Field_Hutang_Detail_Catatan;
    private javax.swing.JTextField Field_Hutang_Detail_Denda;
    private javax.swing.JTextField Field_Hutang_Detail_Harga_Total;
    private javax.swing.JTextField Field_Hutang_Detail_Id_Pelanggan;
    private javax.swing.JTextField Field_Hutang_Detail_Jatuh_Tempo;
    private javax.swing.JTextField Field_Hutang_Detail_Kasir;
    private javax.swing.JTextField Field_Hutang_Detail_No_Hutang;
    private javax.swing.JTextField Field_Hutang_Detail_No_Transaksi;
    private javax.swing.JTextField Field_Hutang_Detail_Pelanggan;
    private javax.swing.JComboBox<String> Field_Hutang_Detail_Status;
    private javax.swing.JTextField Field_Hutang_Detail_Tanggal_Hutang;
    private javax.swing.JTextField Field_Hutang_Detail_Terlambat;
    private javax.swing.JTextArea Field_Hutang_Tambah_Alamat;
    private javax.swing.JTextField Field_Hutang_Tambah_Barang_Barang;
    private javax.swing.JTextArea Field_Hutang_Tambah_Catatan;
    private javax.swing.JTextField Field_Hutang_Tambah_Denda;
    private javax.swing.JTextField Field_Hutang_Tambah_Harga_Total;
    private javax.swing.JTextField Field_Hutang_Tambah_Id_Pelanggan;
    private javax.swing.JTextField Field_Hutang_Tambah_Jatuh_Tempo;
    private javax.swing.JTextField Field_Hutang_Tambah_Kasir;
    private javax.swing.JTextField Field_Hutang_Tambah_No_Hutang;
    private javax.swing.JTextField Field_Hutang_Tambah_No_Telepon;
    private javax.swing.JTextField Field_Hutang_Tambah_No_Telepon1;
    private javax.swing.JTextField Field_Hutang_Tambah_No_Transaksi;
    private javax.swing.JTextField Field_Hutang_Tambah_Pelanggan;
    private javax.swing.JTextField Field_Hutang_Tambah_Tanggal_Hutang;
    private javax.swing.JLabel Lb_Daftar_Hutang;
    private javax.swing.JLabel Lb_Daftar_Hutang1;
    private javax.swing.JLabel Lb_Detail_Barang_Hutang;
    private javax.swing.JLabel Lb_Hutang;
    private javax.swing.JLabel Lb_Hutang_Cari_No_Hutang;
    private javax.swing.JLabel Lb_Hutang_Detail_Alamat;
    private javax.swing.JLabel Lb_Hutang_Detail_Catatan;
    private javax.swing.JLabel Lb_Hutang_Detail_Denda;
    private javax.swing.JLabel Lb_Hutang_Detail_Harga_Total;
    private javax.swing.JLabel Lb_Hutang_Detail_Id_Pelanggan;
    private javax.swing.JLabel Lb_Hutang_Detail_Jatuh_Tempo;
    private javax.swing.JLabel Lb_Hutang_Detail_Nama_Kasir;
    private javax.swing.JLabel Lb_Hutang_Detail_Nama_Pelanggan;
    private javax.swing.JLabel Lb_Hutang_Detail_No_Hutang;
    private javax.swing.JLabel Lb_Hutang_Detail_No_Telepon;
    private javax.swing.JLabel Lb_Hutang_Detail_No_Transaksi;
    private javax.swing.JLabel Lb_Hutang_Detail_Status;
    private javax.swing.JLabel Lb_Hutang_Detail_Tanggal_Hutang;
    private javax.swing.JLabel Lb_Hutang_Detail_Terlambat;
    private javax.swing.JLabel Lb_Hutang_Tambah_Alamat;
    private javax.swing.JLabel Lb_Hutang_Tambah_Catatan;
    private javax.swing.JLabel Lb_Hutang_Tambah_Denda;
    private javax.swing.JLabel Lb_Hutang_Tambah_Harga_Total;
    private javax.swing.JLabel Lb_Hutang_Tambah_Id_Pelanggan;
    private javax.swing.JLabel Lb_Hutang_Tambah_Jatuh_Tempo;
    private javax.swing.JLabel Lb_Hutang_Tambah_Nama_Kasir;
    private javax.swing.JLabel Lb_Hutang_Tambah_Nama_Pelanggan;
    private javax.swing.JLabel Lb_Hutang_Tambah_No_Hutang;
    private javax.swing.JLabel Lb_Hutang_Tambah_No_Telepon;
    private javax.swing.JLabel Lb_Hutang_Tambah_No_Transaksi;
    private javax.swing.JLabel Lb_Hutang_Tambah_Tanggal_Hutang;
    private javax.swing.JTable Tbl_Daftar_Detail_Barang_Hutang;
    private javax.swing.JTable Tbl_Daftar_Hutang;
    private javax.swing.JTable Tbl_Detail_Barang_Hutang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pn_Daftar_Hutang;
    private javax.swing.JPanel pn_Detail_Hutang;
    private javax.swing.JPanel pn_Hutang;
    private javax.swing.JPanel pn_Konten_Hutang;
    private javax.swing.JPanel pn_Tambah_Hutang;
    // End of variables declaration//GEN-END:variables
}
