/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utama;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class User extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Beranda
     */
    public User() {
        initComponents();
        
        getColumnD();
        getDataD();
    }
    
    public void getColumnD() {
        model.addColumn("ID");
        model.addColumn("Nama User");
        model.addColumn("Password ");
        model.addColumn("Akses");
        model.addColumn("Nama Lengkap");
        model.addColumn("No Identitas");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telepon");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Email");
        model.addColumn("Status");
        model.addColumn("Tanggal Mulai");
        model.addColumn("Gaji");
        model.addColumn("No Rek");
        model.addColumn("Alamat");
        Tbl_Daftar_User.setModel(model);

    }

    public void getDataD() {

        ResultSet hasil = db.ambilData("SELECT * FROM pengguna");
        try {
            while (hasil.next()) {
                model.addRow(new Object[]{hasil.getString("id_username"),
                    hasil.getString("username"),hasil.getString("password"), 
                    hasil.getString("Akses"),hasil.getString("Nama_Lengkap"),
                    hasil.getString("No_Identitas"), hasil.getString("Jenis_Kelamin"),
                    hasil.getString("No_Telepon"), hasil.getString("Tanggal_Lahir"),
                    hasil.getString("email"), hasil.getString("Status_Karyawan"),
                    hasil.getString("Tanggal_Mulai"), hasil.getString("Gaji"),
                    hasil.getString("No_Rekening"),hasil.getString("Alamat")});
            }
            Tbl_Daftar_User.setModel(model);
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_User = new javax.swing.JPanel();
        Lb_User = new javax.swing.JLabel();
        Btn_Daftar_User = new javax.swing.JButton();
        Btn_Tambah_User = new javax.swing.JButton();
        pn_Konten_User = new javax.swing.JPanel();
        pn_Daftar_User = new javax.swing.JPanel();
        Lb_Daftar_User = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Daftar_User = new javax.swing.JTable();
        pn_Tambah_Daftar_User = new javax.swing.JPanel();
        Lb_Tambah_User = new javax.swing.JLabel();
        Lb_Tambah_User_ID = new javax.swing.JLabel();
        Lb_Tambah_User_Password = new javax.swing.JLabel();
        Lb_Tambah_User_Nama = new javax.swing.JLabel();
        Lb_Tambah_User_Akses = new javax.swing.JLabel();
        Field_Tambah_User_ID = new javax.swing.JTextField();
        Field_Tambah_User_Password = new javax.swing.JTextField();
        Field_Tambah_User_Nama = new javax.swing.JTextField();
        FIeld_Tambah_User_Akses = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Lb_Data_Karyawan_Nama_Lengkap = new javax.swing.JLabel();
        Field_Data_Karyawan_Nama_Lengkap = new javax.swing.JTextField();
        Lb_Data_Karyawan_Jenis_Kelamin = new javax.swing.JLabel();
        Field_Data_Karyawan_Jenis_Kelamin = new javax.swing.JTextField();
        Lb_Data_Karyawan_No_Telepon = new javax.swing.JLabel();
        Field_Data_Karyawan_No_Telepon = new javax.swing.JTextField();
        Lb_Data_Karyawan_Tanggal_Lahir = new javax.swing.JLabel();
        Field_Data_Karyawan_Tanggal_Lahir = new javax.swing.JTextField();
        Lb_Data_Karyawan_Status = new javax.swing.JLabel();
        Lb_Data_Karyawan_Gaji = new javax.swing.JLabel();
        Field_Data_Karyawan_Gaji = new javax.swing.JTextField();
        Lb_Data_Karyawan_No_Rek = new javax.swing.JLabel();
        Field_Data_Karyawan_No_Rek = new javax.swing.JTextField();
        Field_Data_Karyawan_Status = new javax.swing.JComboBox<>();
        Field_Data_Karyawan_No_Identitas = new javax.swing.JTextField();
        Lb_Data_Karyawan_No_Identitas = new javax.swing.JLabel();
        Lb_Data_Karyawan_Alamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Field_Data_Karyawan_Alamat = new javax.swing.JTextArea();
        Field_Data_Karyawan_Tanggal_Mulai = new javax.swing.JTextField();
        Lb_Data_Karyawan_Tanggal_Mulai = new javax.swing.JLabel();
        Btn_Tambah_User_Simpan = new javax.swing.JButton();
        Lb_Data_Karyawan_Email = new javax.swing.JLabel();
        Field_Data_Karyawan_Email = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1182, 686));

        pn_User.setBackground(new java.awt.Color(255, 255, 255));
        pn_User.setPreferredSize(new java.awt.Dimension(1182, 686));

        Lb_User.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Lb_User.setText("User");

        Btn_Daftar_User.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Btn_Daftar_User.setText("Daftar User");
        Btn_Daftar_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Daftar_UserMouseClicked(evt);
            }
        });

        Btn_Tambah_User.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Btn_Tambah_User.setText("Tambah Daftar User");
        Btn_Tambah_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Tambah_UserMouseClicked(evt);
            }
        });

        pn_Konten_User.setLayout(new java.awt.CardLayout());

        Lb_Daftar_User.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Daftar_User.setText("Daftar User");

        Tbl_Daftar_User.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        Tbl_Daftar_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama User", "Password", "Akses", "Nama Lengkap", "No Identitas", "Jenis Kelamin", "No Telepon", "Tanggal Lahir", "Email", "Status", "Tanggal Mulai", "Gaji", "No Rek", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Daftar_User.setRowHeight(30);
        jScrollPane1.setViewportView(Tbl_Daftar_User);
        if (Tbl_Daftar_User.getColumnModel().getColumnCount() > 0) {
            Tbl_Daftar_User.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout pn_Daftar_UserLayout = new javax.swing.GroupLayout(pn_Daftar_User);
        pn_Daftar_User.setLayout(pn_Daftar_UserLayout);
        pn_Daftar_UserLayout.setHorizontalGroup(
            pn_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Daftar_UserLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(pn_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_UserLayout.createSequentialGroup()
                        .addComponent(Lb_Daftar_User)
                        .addGap(665, 665, 665))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_UserLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        pn_Daftar_UserLayout.setVerticalGroup(
            pn_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Daftar_UserLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Lb_Daftar_User)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pn_Konten_User.add(pn_Daftar_User, "card2");

        Lb_Tambah_User.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Lb_Tambah_User.setText("Tambah User");

        Lb_Tambah_User_ID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_User_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_User_ID.setText("User ID :");

        Lb_Tambah_User_Password.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_User_Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_User_Password.setText("Password :");

        Lb_Tambah_User_Nama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_User_Nama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_User_Nama.setText("Nama User :");

        Lb_Tambah_User_Akses.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Tambah_User_Akses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Tambah_User_Akses.setText("Akses :");

        Field_Tambah_User_ID.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        Field_Tambah_User_ID.setEnabled(false);

        Field_Tambah_User_Password.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Field_Tambah_User_Nama.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        FIeld_Tambah_User_Akses.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        FIeld_Tambah_User_Akses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Karyawan", " " }));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Karyawan");

        Lb_Data_Karyawan_Nama_Lengkap.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Nama_Lengkap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Nama_Lengkap.setText("Nama Lengkap :");

        Field_Data_Karyawan_Nama_Lengkap.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_Jenis_Kelamin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Jenis_Kelamin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Jenis_Kelamin.setText("Jenis Kelamin :");

        Field_Data_Karyawan_Jenis_Kelamin.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_No_Telepon.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_No_Telepon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_No_Telepon.setText("No Telepon :");

        Field_Data_Karyawan_No_Telepon.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_Tanggal_Lahir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Tanggal_Lahir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Tanggal_Lahir.setText("Tanggal Lahir :");

        Field_Data_Karyawan_Tanggal_Lahir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_Status.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Status.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Status.setText("Status Karyawan :");

        Lb_Data_Karyawan_Gaji.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Gaji.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Gaji.setText("Gaji :");

        Field_Data_Karyawan_Gaji.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_No_Rek.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_No_Rek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_No_Rek.setText("No Rek :");

        Field_Data_Karyawan_No_Rek.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Field_Data_Karyawan_Status.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        Field_Data_Karyawan_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kontrak", "Paruh Waktu", "Penuh Waktu", " " }));
        Field_Data_Karyawan_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Data_Karyawan_StatusActionPerformed(evt);
            }
        });

        Field_Data_Karyawan_No_Identitas.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_No_Identitas.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_No_Identitas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_No_Identitas.setText("No Identitas :");

        Lb_Data_Karyawan_Alamat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Alamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Alamat.setText("Alamat :");

        Field_Data_Karyawan_Alamat.setColumns(20);
        Field_Data_Karyawan_Alamat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Field_Data_Karyawan_Alamat.setRows(5);
        jScrollPane2.setViewportView(Field_Data_Karyawan_Alamat);

        Field_Data_Karyawan_Tanggal_Mulai.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        Lb_Data_Karyawan_Tanggal_Mulai.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Tanggal_Mulai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Tanggal_Mulai.setText("Tanggal Mulai :");

        Btn_Tambah_User_Simpan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Btn_Tambah_User_Simpan.setText("Simpan");
        Btn_Tambah_User_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Tambah_User_SimpanMouseClicked(evt);
            }
        });
        Btn_Tambah_User_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tambah_User_SimpanActionPerformed(evt);
            }
        });

        Lb_Data_Karyawan_Email.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_Data_Karyawan_Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Data_Karyawan_Email.setText("Email :");

        Field_Data_Karyawan_Email.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        javax.swing.GroupLayout pn_Tambah_Daftar_UserLayout = new javax.swing.GroupLayout(pn_Tambah_Daftar_User);
        pn_Tambah_Daftar_User.setLayout(pn_Tambah_Daftar_UserLayout);
        pn_Tambah_Daftar_UserLayout.setHorizontalGroup(
            pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addComponent(Lb_Tambah_User_Akses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FIeld_Tambah_User_Akses, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_Tambah_User_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249)
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lb_Data_Karyawan_Tanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_Data_Karyawan_No_Identitas, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lb_Data_Karyawan_Jenis_Kelamin, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(Lb_Data_Karyawan_Nama_Lengkap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lb_Data_Karyawan_No_Telepon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lb_Data_Karyawan_Status, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Field_Data_Karyawan_No_Telepon)
                            .addComponent(Field_Data_Karyawan_Jenis_Kelamin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Field_Data_Karyawan_Nama_Lengkap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Field_Data_Karyawan_No_Identitas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Field_Data_Karyawan_Tanggal_Lahir)
                            .addComponent(Field_Data_Karyawan_Status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Lb_Data_Karyawan_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field_Data_Karyawan_Email)))
                .addContainerGap(595, Short.MAX_VALUE))
            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Tambah_User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(414, 414, 414))
            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_User_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Tambah_User_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addComponent(Lb_Tambah_User_Password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_Tambah_User_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Lb_Tambah_User_Nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field_Tambah_User_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lb_Data_Karyawan_Tanggal_Mulai)
                            .addComponent(Lb_Data_Karyawan_Gaji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Field_Data_Karyawan_Tanggal_Mulai)
                            .addComponent(Field_Data_Karyawan_Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Lb_Data_Karyawan_No_Rek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field_Data_Karyawan_No_Rek, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Lb_Data_Karyawan_Alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        pn_Tambah_Daftar_UserLayout.setVerticalGroup(
            pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Tambah_User)
                    .addComponent(jLabel1))
                .addGap(70, 70, 70)
                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addComponent(Lb_Data_Karyawan_Nama_Lengkap)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addComponent(Field_Data_Karyawan_Nama_Lengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addComponent(Field_Data_Karyawan_No_Identitas, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(29, 29, 29)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Data_Karyawan_Jenis_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Data_Karyawan_Jenis_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Field_Data_Karyawan_Tanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lb_Data_Karyawan_Tanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Field_Data_Karyawan_No_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lb_Data_Karyawan_No_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)))
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Data_Karyawan_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Data_Karyawan_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Data_Karyawan_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Data_Karyawan_Status)
                                    .addComponent(Btn_Tambah_User_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(190, 190, 190))
                            .addComponent(Lb_Data_Karyawan_No_Identitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Tambah_User_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Field_Tambah_User_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_Tambah_User_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Tambah_User_Password))
                        .addGap(33, 33, 33)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_Tambah_User_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Tambah_User_Nama))
                        .addGap(30, 30, 30)
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FIeld_Tambah_User_Akses, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Tambah_User_Akses))
                        .addContainerGap())
                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                        .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Data_Karyawan_No_Rek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Data_Karyawan_No_Rek))
                                .addGap(29, 29, 29)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lb_Data_Karyawan_Alamat)))
                            .addGroup(pn_Tambah_Daftar_UserLayout.createSequentialGroup()
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Field_Data_Karyawan_Tanggal_Mulai, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(Lb_Data_Karyawan_Tanggal_Mulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(pn_Tambah_Daftar_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Field_Data_Karyawan_Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Data_Karyawan_Gaji))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pn_Konten_User.add(pn_Tambah_Daftar_User, "card3");

        javax.swing.GroupLayout pn_UserLayout = new javax.swing.GroupLayout(pn_User);
        pn_User.setLayout(pn_UserLayout);
        pn_UserLayout.setHorizontalGroup(
            pn_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_UserLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_UserLayout.createSequentialGroup()
                        .addComponent(Btn_Daftar_User, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(Btn_Tambah_User, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Lb_User, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Konten_User, javax.swing.GroupLayout.PREFERRED_SIZE, 1570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pn_UserLayout.setVerticalGroup(
            pn_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_UserLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Lb_User)
                .addGap(64, 64, 64)
                .addGroup(pn_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Daftar_User, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Tambah_User, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(pn_Konten_User, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_User, javax.swing.GroupLayout.PREFERRED_SIZE, 1721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_User, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Daftar_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Daftar_UserMouseClicked
        pn_Konten_User.removeAll();
        pn_Konten_User.repaint();
        pn_Konten_User.revalidate();
        
        pn_Konten_User.add(pn_Daftar_User);
        pn_Konten_User.repaint();
        pn_Konten_User.revalidate();
    }//GEN-LAST:event_Btn_Daftar_UserMouseClicked

    private void Btn_Tambah_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Tambah_UserMouseClicked
        pn_Konten_User.removeAll();
        pn_Konten_User.repaint();
        pn_Konten_User.revalidate();
        
        pn_Konten_User.add(pn_Tambah_Daftar_User);
        pn_Konten_User.repaint();
        pn_Konten_User.revalidate();
    }//GEN-LAST:event_Btn_Tambah_UserMouseClicked

    private void Field_Data_Karyawan_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Data_Karyawan_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Data_Karyawan_StatusActionPerformed

    private void Btn_Tambah_User_SimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Tambah_User_SimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Tambah_User_SimpanMouseClicked

    private void Btn_Tambah_User_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tambah_User_SimpanActionPerformed
        String id_username = Field_Tambah_User_ID.getText();
        String username = Field_Tambah_User_Nama.getText();
        String password = Field_Tambah_User_Password.getText();
        String email = Field_Data_Karyawan_Email.getText();
        String Nama_Lengkap = Field_Data_Karyawan_Nama_Lengkap.getText();
        String No_Identitas = Field_Data_Karyawan_No_Identitas.getText();
        String Jenis_Kelamin = Field_Data_Karyawan_Jenis_Kelamin.getText();
        String No_Telepon = Field_Data_Karyawan_No_Telepon.getText();
        String Tanggal_Lahir = Field_Data_Karyawan_Tanggal_Lahir.getText();
        String Tanggal_Mulai = Field_Data_Karyawan_Tanggal_Mulai.getText();
        String Gaji = Field_Data_Karyawan_Gaji.getText();
        String No_Rekening = Field_Data_Karyawan_No_Rek.getText();
        String Alamat = Field_Data_Karyawan_Alamat.getText();

        String Akses = String.valueOf(FIeld_Tambah_User_Akses.getSelectedItem());
        String Status_Karyawan = String.valueOf(Field_Data_Karyawan_Status.getSelectedItem());


        db.aksi("INSERT INTO pengguna VALUES ('" + id_username +"','"+ username + "','" + password + "','" + email + "','" + Akses + "','" + Nama_Lengkap + "','" + No_Identitas + "','" + Jenis_Kelamin + "','" + No_Telepon + "','" + Tanggal_Lahir + "','" + Status_Karyawan + "','" + Tanggal_Mulai + "','" + Gaji + "','" + No_Rekening + "','" + Alamat + "')");
        model.setRowCount(0);
        Tbl_Daftar_User.setModel(model);
        getColumnD();
        getDataD();
    }//GEN-LAST:event_Btn_Tambah_User_SimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Daftar_User;
    private javax.swing.JButton Btn_Tambah_User;
    private javax.swing.JButton Btn_Tambah_User_Simpan;
    private javax.swing.JComboBox<String> FIeld_Tambah_User_Akses;
    private javax.swing.JTextArea Field_Data_Karyawan_Alamat;
    private javax.swing.JTextField Field_Data_Karyawan_Email;
    private javax.swing.JTextField Field_Data_Karyawan_Gaji;
    private javax.swing.JTextField Field_Data_Karyawan_Jenis_Kelamin;
    private javax.swing.JTextField Field_Data_Karyawan_Nama_Lengkap;
    private javax.swing.JTextField Field_Data_Karyawan_No_Identitas;
    private javax.swing.JTextField Field_Data_Karyawan_No_Rek;
    private javax.swing.JTextField Field_Data_Karyawan_No_Telepon;
    private javax.swing.JComboBox<String> Field_Data_Karyawan_Status;
    private javax.swing.JTextField Field_Data_Karyawan_Tanggal_Lahir;
    private javax.swing.JTextField Field_Data_Karyawan_Tanggal_Mulai;
    private javax.swing.JTextField Field_Tambah_User_ID;
    private javax.swing.JTextField Field_Tambah_User_Nama;
    private javax.swing.JTextField Field_Tambah_User_Password;
    private javax.swing.JLabel Lb_Daftar_User;
    private javax.swing.JLabel Lb_Data_Karyawan_Alamat;
    private javax.swing.JLabel Lb_Data_Karyawan_Email;
    private javax.swing.JLabel Lb_Data_Karyawan_Gaji;
    private javax.swing.JLabel Lb_Data_Karyawan_Jenis_Kelamin;
    private javax.swing.JLabel Lb_Data_Karyawan_Nama_Lengkap;
    private javax.swing.JLabel Lb_Data_Karyawan_No_Identitas;
    private javax.swing.JLabel Lb_Data_Karyawan_No_Rek;
    private javax.swing.JLabel Lb_Data_Karyawan_No_Telepon;
    private javax.swing.JLabel Lb_Data_Karyawan_Status;
    private javax.swing.JLabel Lb_Data_Karyawan_Tanggal_Lahir;
    private javax.swing.JLabel Lb_Data_Karyawan_Tanggal_Mulai;
    private javax.swing.JLabel Lb_Tambah_User;
    private javax.swing.JLabel Lb_Tambah_User_Akses;
    private javax.swing.JLabel Lb_Tambah_User_ID;
    private javax.swing.JLabel Lb_Tambah_User_Nama;
    private javax.swing.JLabel Lb_Tambah_User_Password;
    private javax.swing.JLabel Lb_User;
    private javax.swing.JTable Tbl_Daftar_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_Daftar_User;
    private javax.swing.JPanel pn_Konten_User;
    private javax.swing.JPanel pn_Tambah_Daftar_User;
    private javax.swing.JPanel pn_User;
    // End of variables declaration//GEN-END:variables
}
